[target.armv7-unknown-linux-gnueabihf]
pre-build = [
    "dpkg --add-architecture armhf",
    "apt-get update",
    "apt-get install -y libzmq3-dev:armhf libssl-dev:armhf protobuf-compiler libprotobuf-dev"
]

