---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: classifier
  namespace: {{ .Release.Namespace }}
  labels:
    app: classifier
    {{- include "krewetka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.classifier.replicas | int }}
  selector:
    matchLabels:
      app: classifier
      {{- include "krewetka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: classifier
        {{- include "krewetka.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.registry.imagePullSecrets }}
      containers:
      - name: classifier
        image: "{{ .Values.registry.url }}/{{ .Values.classifier.image }}:{{ .Values.classifier.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: {{ .Values.classifier.grpcServerPort }}
          name: grpc
        envFrom:
        - configMapRef:
            name: {{ .Values.classifier.configMap.name }}
