---
apiVersion: v1
kind: Service
metadata:
  name: classifier-svc
  labels:
    app: classifier
    {{- include "krewetka.labels" . | nindent 4 }}
spec:
  selector:
    app: classifier
    {{- include "krewetka.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: {{ .Values.classifier.grpcServerPort }}
      targetPort: {{ .Values.classifier.grpcServerPort }}

