---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reporting
  namespace: {{ .Release.Namespace }}
  labels:
    app: reporting
    {{- include "krewetka.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.processor.replicas | int }}
  selector:
    matchLabels:
      app: reporting
      {{- include "krewetka.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: reporting
        {{- include "krewetka.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: {{ .Values.registry.imagePullSecrets }}
      containers:
      - name: reporting
        image: "{{ .Values.registry.url }}/{{ .Values.reporting.image }}:{{ .Values.reporting.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            port: 8080
            path: /healthz
          initialDelaySeconds: {{ .Values.reporting.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.reporting.livenessProbe.periodSeconds }}
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 999
        envFrom:
        - configMapRef:
            name: {{ .Values.reporting.configMap.name }}
        - secretRef:
            name: {{ .Values.reporting.secret.name }}
