apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-reporting
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /analytics(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: reporting-svc
                port:
                  number: 8080
