---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.reporting.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: reporting
    {{- include "krewetka.labels" . | nindent 4 }}
type: Opaque
stringData:
  KREWETKA__CLICKHOUSE_USER: {{ .Values.config.clickhouse.user | quote }}
  KREWETKA__CLICKHOUSE_PASSWORD: {{ .Values.config.clickhouse.password | quote }}
