---
apiVersion: v1
kind: Service
metadata:
  name: reporting-svc
  labels:
    app: reporting
    {{- include "krewetka.labels" . | nindent 4 }}
spec:
  selector:
    app: reporting
    {{- include "krewetka.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080

