processor:
  configMap:
    name: processor-config
  secret:
    name: processor-secret
  replicas: 2
  image: processor
  version: latest
  livenessProbe:
    initialDelaySeconds: 3
    periodSeconds: 3
  migrationJob:
    restartPolicy: OnFailure
    backoffLimit: 5
    # image: migrator
    # version: 0.0.1
  classifierHost: classifier.krewetka.svc.cluster.local

classifier:
  configMap:
    name: classifier-config
  replicas: 2
  image: classifier
  version: latest

  grpcServerPort: 50051

reporting:
  configMap:
    name: reporting-config
  secret:
    name: reporting-secret
  replicas: 1
  image: reporting
  version: latest
  livenessProbe:
    initialDelaySeconds: 3
    periodSeconds: 3

  ui:
    image: reporting-ui
    version: latest
    replicas: 1


registry:
  imagePullSecrets: regcred
  url:

imagePullPolicy: Always
