kafka:
  provisioning:
    numPartitions: 2
    replicationFactor: 1
    enabled: true
    topics: 
      - name: flows
        replicationFactor: 1
      - name: flows_retry_1
        replicationFactor: 1
      - name: flows_retry_2
        replicationFactor: 1
      - name: flows_dead_letter_queue
        replicationFactor: 1

    parallel: 5
  externalAccess:
    enabled: true
    service:
      type: LoadBalancer
      ports:
        external: 9094
    autoDiscovery:
      enabled: true
  serviceAccount:
    create: true
  rbac:
    create: true
  zookeeper:
    enabled: false
  externalZookeeper:
    servers:
      - "zookeeper.krewetka.svc.cluster.local"
  fullnameOverride: kafka

clickhouse:
  fullnameOverride: clickhouse
  zookeeper:
    enabled: false
  externalZookeeper.servers:
    servers:
      - "zookeeper.krewetka.svc.cluster.local"
  auth:
    username: myuser
    password: mypassword
  shards: 1
  replicaCount: 1

zookeeper:
  fullnameOverride: zookeeper

krewetka:
  registry:
    url: testing-registry:35945

  processor:
    image: krewetka/processor
    migrationJob:
      image: krewetka/migrator

  classifier:
    image: krewetka/classifier

  config:
    clickhouse:
      user: myuser
      password: mypassword # TODO sealed secrets
      port: 9000
      host: clickhouse.krewetka.svc.cluster.local

    kafka:
      brokers: "kafka.krewetka.svc.cluster.local:9092"
      topic: flows

    classifier:
      port: 50051
      host: classifier








