---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.processor.configMap.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: processor
    {{- include "krewetka.labels" . | nindent 4 }}
data:
  KREWETKA__KAFKA_BROKERS: {{ .Values.config.kafka.brokers | quote }}
  KREWETKA__KAFKA_TOPIC: {{ .Values.config.kafka.topic | quote }}
  KREWETKA__CLICKHOUSE_SETTINGS__HOST: {{ .Values.config.clickhouse.host | quote }}
  KREWETKA__CLICKHOUSE_SETTINGS__PORT: {{ .Values.config.clickhouse.port | quote}}
  KREWETKA__GRPC_CLASSIFICATION_PORT: {{ .Values.classifier.grpcServerPort | quote}}
  KREWETKA__GRPC_CLASSIFICATION_HOST: {{ .Values.config.classifier.host | quote }}
  RUST_LOG: {{ .Values.processor.logLevel | quote | default "info"}}

