apiVersion: batch/v1
kind: Job
metadata:
  name: processor-migration
  namespace: {{ .Release.Namespace }}
  labels:
    app: processor-migration
    {{- include "krewetka.labels" . | nindent 4 }}
spec:
  template:
    spec:
      imagePullSecrets:
        - name: {{ .Values.registry.imagePullSecrets }}
      containers:
      - name: processor-migration
        image: "{{ .Values.registry.url }}/{{ .Values.processor.image }}:{{ .Values.processor.version }}"
        imagePullPolicy: {{ .Values.imagePullPolicy }}
        command: ["./processor-migrator"]
        args: ["apply", "/app/migrations"]
        envFrom:
        - secretRef:
              name: {{ .Values.processor.secret.name }}
        env:
          - name: KREWETKA__CLICKHOUSE_SETTINGS__HOST
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.processor.configMap.name }}
                key: KREWETKA__CLICKHOUSE_SETTINGS__HOST
          - name: KREWETKA__CLICKHOUSE_SETTINGS__PORT
            valueFrom:
              configMapKeyRef:
                name: {{ .Values.processor.configMap.name }}
                key: KREWETKA__CLICKHOUSE_SETTINGS__PORT

      restartPolicy: {{ .Values.processor.migrationJob.restartPolicy | quote }}
  # backoffLimit: {{ .Values.processor.migrationJob.backoffLimit }}

