---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.processor.secret.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: processor
    {{- include "krewetka.labels" . | nindent 4 }}
type: Opaque
stringData:
  KREWETKA__CLICKHOUSE_SETTINGS__USER: {{ .Values.config.clickhouse.user | quote }}
  KREWETKA__CLICKHOUSE_SETTINGS__PASSWORD: {{ .Values.config.clickhouse.password | quote }}
