---
apiVersion: v1
kind: Service
metadata:
  name: reporting-ui-svc
  labels:
    app: reporting-ui
    {{- include "krewetka.labels" . | nindent 4 }}
spec:
  selector:
    app: reporting-ui
    {{- include "krewetka.selectorLabels" . | nindent 4 }}
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000

