name: docker_build

on: [ workflow_call ]
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      fail-fast: false
      matrix:
        app: ["collector", "processor", "reporting"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and tag image of ${{ matrix.app }}
        uses: docker/build-push-action@v3
        with:
          context: ./
          file: ./${{ matrix.app }}/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: false
          tags: ${{ matrix.app }}:latest
