name: docker_build

on: [ workflow_call ]
jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      fail-fast: false
      matrix:
        dir_app_pairs: [{"dir": "processor", "app": "processor"}, {"dir":"reporting", "app": "reporting"},{"dir": "frontend", "app": "reporting-ui"}, {"dir":"classification", "app": "classifier"}]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to ACR
        uses: docker/login-action@v2
        with:
          registry: regcred.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_TOKEN }}

      - name: Build and tag image of ${{ matrix.dir_app_pairs }}
        uses: docker/build-push-action@v3
        with:
          context: ./${{matrix.dir_app_pairs.dir}}
          builder: ${{ steps.buildx.outputs.name }}
          push: ${{ github.ref == 'refs/heads/master' }}
          tags: regcred.azurecr.io/${{ matrix.dir_app_pairs.app }}:latest
