name: Testing action
on: [push]

jobs:
  test_and_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Protoc
        uses: arduino/setup-protoc@v1

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo

      - name: Target cache
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-target

      - name: Test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --verbose

      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy

      - name: Fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check


  build_collector_bin:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - armv7-unknown-linux-gnueabihf

    steps:
      - uses: actions/checkout@v3

      - name: Cargo cache
        uses: actions/cache@v3
        with:
          path: ~/.cargo
          key: ${{ runner.os }}-cargo-processor-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-processor-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-processor

      - name: Target cache
        uses: actions/cache@v3
        with:
          path: target
          key: ${{ runner.os }}-cargo-target-processor-${{ hashFiles('Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-target-processor-${{ hashFiles('Cargo.lock') }}
            ${{ runner.os }}-cargo-target-processor

      - name: Get cross
        run: wget -c https://github.com/cross-rs/cross/releases/download/v0.2.4/cross-x86_64-unknown-linux-gnu.tar.gz -O - | tar -xz

      - name: Build
        run: ./cross build --target ${{matrix.target}} --manifest-path=Cargo.toml -p=krewetka-collector
